import Joi from "joi";

export const createProductSchema = Joi.object({
  itemName: Joi.string().trim().min(1).required(),
  itemHsn: Joi.string().optional().allow(""),
  itemCode: Joi.string().optional().allow(""),
  barcode: Joi.string().optional().allow(""),
  purchaseRate: Joi.number().min(0).optional(),
  retailRate: Joi.number().min(0).required(),
  wholesaleRate: Joi.number().min(0).optional(),
  unitPrimary: Joi.string().optional().allow(""),
  unitSecondary: Joi.string().optional().allow(""),
  conversionFactor: Joi.number().min(0).optional(),
  discountAmount: Joi.number().min(0).optional(),
  discountType: Joi.string().valid("Percentage", "Fixed").optional(),
  warehouse: Joi.string().optional().allow(""),
  taxPercentage: Joi.number().min(0).optional(),
  batchEnabled: Joi.boolean().optional(),
  serialNumberEnabled: Joi.boolean().optional(),
  enabledOpeningStock: Joi.boolean().optional(),
  purchaseTax: Joi.string().valid("include", "exclude").optional(),
  retailTax: Joi.string().valid("include", "exclude").optional(),
  wholesaleTax: Joi.string().valid("include", "exclude").optional(),
  category: Joi.string().required(),
  stock: Joi.number().min(0).optional(),
});

export const updateProductSchema = Joi.object({
  itemName: Joi.string().trim().min(1).required(),
  itemHsn: Joi.string().optional().allow(""),
  itemCode: Joi.string().optional().allow(""),
  barcode: Joi.string().optional().allow(""),
  purchaseRate: Joi.number().min(0).optional(),
  retailRate: Joi.number().min(0).required(),
  wholesaleRate: Joi.number().min(0).optional(),
  unitPrimary: Joi.string().optional().allow(""),
  unitSecondary: Joi.string().optional().allow(""),
  conversionFactor: Joi.number().min(0).optional(),
  discountAmount: Joi.number().min(0).optional(),
  discountType: Joi.string().valid("Percentage", "Fixed").optional(),
  warehouse: Joi.string().optional().allow(""),
  taxPercentage: Joi.number().min(0).optional(),
  batchEnabled: Joi.boolean().optional(),
  serialNumberEnabled: Joi.boolean().optional(),
  enabledOpeningStock: Joi.boolean().optional(),
  purchaseTax: Joi.string().valid("include", "exclude").optional(),
  retailTax: Joi.string().valid("include", "exclude").optional(),
  wholesaleTax: Joi.string().valid("include", "exclude").optional(),
  category: Joi.string().required(),
  stock: Joi.number().min(0).optional(),
});
